### NumPy Fundamentals

---

##### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

---

##### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

---

##### 1. Creating Numpy Arrays

Creating 1D numpy array

In [103]:
# np.array
# We need to import numpy library
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


Creating 2D numpy array

In [104]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


Creating 3D numpy array

In [105]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Checking dtype of datatype

In [4]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

Creating numpy array using arange function

In [5]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

Creating numpy array with reshape

In [118]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

Creating array with all element as 1

In [120]:
np.ones((3,4))

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

Creating array with all element as 0

In [121]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Creating array with random values

In [127]:
np.random.random((3,4))

array([[0.92751024, 0.05886578, 0.08395133, 0.17772576],
       [0.63497829, 0.88692324, 0.19378928, 0.51265406],
       [0.43270329, 0.93714293, 0.56712968, 0.21992097]])

Creating array with linear spacing

In [135]:
np.linspace(-10,10,50)

array([-10.        ,  -9.59183673,  -9.18367347,  -8.7755102 ,
        -8.36734694,  -7.95918367,  -7.55102041,  -7.14285714,
        -6.73469388,  -6.32653061,  -5.91836735,  -5.51020408,
        -5.10204082,  -4.69387755,  -4.28571429,  -3.87755102,
        -3.46938776,  -3.06122449,  -2.65306122,  -2.24489796,
        -1.83673469,  -1.42857143,  -1.02040816,  -0.6122449 ,
        -0.20408163,   0.20408163,   0.6122449 ,   1.02040816,
         1.42857143,   1.83673469,   2.24489796,   2.65306122,
         3.06122449,   3.46938776,   3.87755102,   4.28571429,
         4.69387755,   5.10204082,   5.51020408,   5.91836735,
         6.32653061,   6.73469388,   7.14285714,   7.55102041,
         7.95918367,   8.36734694,   8.7755102 ,   9.18367347,
         9.59183673,  10.        ])

Creating identity matrix

In [136]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---

##### 2. Array Attributes

Creating 1D, 2D and 3D array

In [139]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Finding the number of dimension

In [142]:
# ndim
a1.ndim

1

Finding the shape of array

In [146]:
# shape
print(a1.shape)
a1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Finding the size of array

In [149]:
# size
print(a3.size)
a3

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Finding itemsize

In [153]:
# itemsize
a1.itemsize

4

Finding datatype

In [154]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


---

##### 3. Changing Datatype

In [167]:
a1 = np.array([1.,2.,3.])
a2 = a1.astype(np.int8)

In [169]:
print(a1.itemsize)
print(a2.itemsize)

8
1


In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

---

##### 4. Array Operations

Creating array

In [172]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
a2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Scalar Operation

In [15]:
# Addition
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [16]:
# Multiplication
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [17]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

2. Vector Operation

In [174]:
# Addition
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [175]:
# Multiplication
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

In [176]:
# relational
a1==a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

---

##### 5. Array Functions

random - create random values

In [186]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 4., 27., 98.],
       [31., 75.,  3.],
       [32., 77.,  2.]])

max/min/sum/prod

In [187]:
# max
print(np.max(a1))
print(np.max(a1, axis=0))
print(np.max(a1, axis=1))

98.0
[32. 77. 98.]
[98. 75. 77.]


In [188]:
# min
print(np.min(a1))
print(np.min(a1, axis=0))
print(np.min(a1, axis=1))

2.0
[ 4. 27.  2.]
[4. 3. 2.]


In [189]:
# sum
print(np.sum(a1))
print(np.sum(a1, axis=0))
print(np.sum(a1, axis=1))

349.0
[ 67. 179. 103.]
[129. 109. 111.]


In [190]:
# product (prod/product)
print(np.product(a1))
print(np.prod(a1, axis=0))
print(np.prod(a1, axis=1))

363801715200.0
[  3968. 155925.    588.]
[10584.  6975.  4928.]


mean/median/std/var

In [191]:
# mean
print(np.mean(a1))
print(np.mean(a1, axis=0))
print(np.mean(a1, axis=1))

38.77777777777778
[22.33333333 59.66666667 34.33333333]
[43.         36.33333333 37.        ]


In [192]:
# median
print(np.median(a1))
print(np.median(a1, axis=0))
print(np.median(a1, axis=1))

31.0
[31. 75.  3.]
[27. 31. 32.]


In [193]:
# standard deviation
print(np.std(a1))
print(np.std(a1, axis=0))
print(np.std(a1, axis=1))

33.940398013045616
[12.97005097 23.11324776 45.02098276]
[40.00833247 29.63481436 30.82207001]


In [194]:
# variance
print(np.var(a1))
print(np.var(a1, axis=0))
print(np.var(a1, axis=1))

1151.9506172839506
[ 168.22222222  534.22222222 2026.88888889]
[1600.66666667  878.22222222  950.        ]


trigonomoetric functions

In [195]:
# sin
np.sin(a1)

array([[-0.7568025 ,  0.95637593, -0.57338187],
       [-0.40403765, -0.38778164,  0.14112001],
       [ 0.55142668,  0.99952016,  0.90929743]])

In [196]:
# cos
np.cos(a1)

array([[-0.65364362, -0.29213881, -0.81928825],
       [ 0.91474236,  0.92175127, -0.9899925 ],
       [ 0.83422336, -0.03097503, -0.41614684]])

In [197]:
# tan
np.tan(a1)

array([[  1.15782128,  -3.2737038 ,   0.69985365],
       [ -0.44169557,  -0.42070095,  -0.14254654],
       [  0.66100604, -32.26857578,  -2.18503986]])

dot product

In [204]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

log

In [40]:
np.log(a1)

C:\Users\SESA702302\AppData\Local\Temp\ipykernel_11272\2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[3.66356165, 4.39444915, 4.02535169],
       [4.31748811, 4.06044301,       -inf],
       [4.18965474, 3.52636052, 3.68887945]])

exponenet

In [41]:
np.exp(a1)

array([[8.65934004e+16, 1.50609731e+35, 2.09165950e+24],
       [3.73324200e+32, 1.54553894e+25, 1.00000000e+00],
       [4.60718663e+28, 5.83461743e+14, 2.35385267e+17]])

round/floor/ceil

In [42]:
# round
np.round(np.random.random((2,3))*100)

array([[94., 10., 14.],
       [70., 76., 52.]])

In [43]:
# floor
np.floor(np.random.random((2,3))*100)

array([[45., 11., 56.],
       [30., 72., 55.]])

In [ ]:
# ceil
np.ceil(np.random.random((2,3))*100)

array([[48.,  4.,  6.],
       [ 3., 18., 82.]])

---

##### 6. Indexing and Slicing

Creating 1D, 2D, 3D arrays

In [206]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

print(a1)
print()
print(a2)
print()

print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [207]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a1[2:5:2]

array([2, 4])

In [63]:
a2[1,0]

4

In [64]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [65]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [66]:
a2[1,::3]

array([4, 7])

In [67]:
a2[0,:]

array([0, 1, 2, 3])

In [68]:
a2[:,2]

array([ 2,  6, 10])

In [69]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [70]:
a3[1,0,1]

10

In [71]:
a3[1,1,0]

12

In [72]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [73]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [74]:
a3[0,1,:]

array([3, 4, 5])

---

##### 7. Iterating

In [215]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
print(a1)

for i in a1:
  print(i)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [216]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [217]:
print(a2)

for i in a2:
  print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [77]:
print(a3)

for i in a3:
  print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


If we want to iterate througfh all the elements of a n-d arraya then we will use nditer method

In [219]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [78]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


---

##### 8. Reshaping

Transpose

In [80]:
# we can use np.transpose or T to transpose a matrix
print(a2)
print(np.transpose(a2))
print(a2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


Ravel

In [82]:
# Ravel returns a flattened, one-dimensional array containing the elements of the original array.
print(a3)
a3.ravel()

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

---

##### 9. Stacking

horizontal stacking

In [223]:
# Creating array
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [84]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

Vertical stacking

In [85]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

---

##### 10. Splitting

horizontal splitting

In [224]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
print(np.hsplit(a4,2))
print(np.hsplit(a4,3))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


ValueError: array split does not result in an equal division

vertical splitting

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [225]:
# print(np.vsplit(a5,2))
print(np.vsplit(a5,3))

[array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]
