### NumPy Fundamentals - TASK

---

In [1]:
import numpy as np

---

##### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [107]:
#Code here
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

# OR
null_vector = np.nan*np.empty(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[nan nan nan nan  1. nan nan nan nan nan]


---

##### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [108]:
#Code here
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

arr = np.random.random(a*b).reshape(a,b)
print()
print("The array is: ", arr)
print()
print("The average of array is: ", np.mean(arr))

# OR
a,b = map(int, input("Enter two numbers: ").split())
x = np.random.random((a,b))
print(x)
print(x.mean())

Enter first number: 2
Enter second number: 3

The array is:  [[0.31329932 0.98285366 0.02990839]
 [0.9526592  0.56515856 0.5502575 ]]

The average of array is:  0.5656894365845583
Enter two numbers: 2 3
[[0.57897822 0.03693792 0.22125375]
 [0.62451668 0.90921879 0.38238098]]
0.4588810565394806


---

##### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [110]:
#Code here

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

def border_zero(a,b):
    arr = np.zeros(a*b).reshape(a,b)
    arr[::arr.shape[0]-1] = 1
    arr[::, ::arr.shape[1]-1] = 1
    return arr

print(border_zero(a,b))

# OR
def borderArray(a,b):
    x = np.ones((a,b))
    x[1:-1, 1:-1] = 0    # Except the border, changing all other elements to 0
    return x
borderArray(4,5)

Enter first number: 4
Enter second number: 5
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

---

##### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [10]:
#Code here
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

---

##### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

#Code here <br>
Identity matrix is only possible for square matrix. Therefore it is not possible to create a identity matrix of we have non-square matrix

---

##### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [113]:
#Code here
z = np.zeros((5,5))
z = z+np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

---

##### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [122]:
#code here
arr = np.random.randint(1, 100, (10,2))
point = np.array([2,3])
np.sqrt(np.sum((arr-point)**2, axis=1)).astype(int)

array([ 90,  37,   5,  70,  83,  29,  93,  93, 107,  63])

---

##### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [131]:
#Code here
arr = np.arange(6*7*8).reshape(6,7,8)

# Get the shape of the array
shape = arr.shape

# Convert linear index to 3D index
index_1d = 99  # 100th element (0-based index)
index_3d = np.unravel_index(index_1d, shape)
print(index_3d)

# OR
np.unravel_index(99, (6,7,8))

(1, 5, 3)


(1, 5, 3)

---

##### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [72]:
#Code here
input_data = "1 2 3 4 -8 -10"
arr = np.array(input_data.split(), dtype = 'float')
np.flip(arr)

array([-10.,  -8.,   4.,   3.,   2.,   1.])

---

##### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [64]:
#Code here
arr = np.array([1, 2])
print(arr.size)
print(len(arr))

2
2


---

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [132]:
#Code here
def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim > 1:
        raise TypeError("Requires 1D Array")
    s = np.sum(np.exp(arr))
    return np.exp(arr)/s

softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

---

##### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [133]:
#Coder here
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
    return np.vstack(args)

a = np.arange(10).reshape(2, -1)
print("a=",a)
b = np.repeat(1, 10).reshape(2, -1)
print("b=",b)
print(vertical_stack(a,b))
c = np.random.random((2,5))
print("c=", c)
vertical_stack(a,b,c)

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c= [[0.11197064 0.0516609  0.01016602 0.42748851 0.83736058]
 [0.56479241 0.34364389 0.36193664 0.48013145 0.65293699]]


array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.11197064, 0.0516609 , 0.01016602, 0.42748851, 0.83736058],
       [0.56479241, 0.34364389, 0.36193664, 0.48013145, 0.65293699]])

---

##### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [134]:
#Code here

def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError
        
    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}

    end = end.split("-")
    end_last = int(end[-1]) + 1
    
    # If the next day of end falls in the next month, account for that
    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f'0{days_diff}' if days_diff< 10 else f'{days_diff}'
        next_month = int(end[-2]) + 1
        end[-2] = f'0{next_month}' if next_month< 10 else f'{next_month}'
    else:
        end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
    end = "-".join(end)
    return np.arange(start, end, dtype="datetime64[D]")    # Use arange() to generate all dates between start and end 
date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

---

##### `Q-14:` Subtract the mean of each row from a matrix.

In [55]:
#code here
arr = np.arange(9).reshape(3,3)
print(arr)
arr - np.mean(arr, axis = 1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[-1., -3., -5.],
       [ 2.,  0., -2.],
       [ 5.,  3.,  1.]])

---

##### `Q-15:` Swap column-1 of array with column-2 in the array.

In [47]:
#Code here
# Create an example array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
# Swap column 1 with column 2
arr[:, [0, 1]] = arr[:, [1, 0]]

# Print the modified array
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 1 3]
 [5 4 6]
 [8 7 9]]


---

##### `Q-16:` Replace odd elements in arrays with -1.

In [45]:
#Code here
a=np.array([6,3,1,5,8])
np.where(a%2 != 0, -1, a)

array([ 6, -1, -1, -1,  8])

---

##### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [136]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

print(np.maximum(a, b))

# OR
a[b>a] = b[a<b]
a

[6 3 1 7 8]


array([6, 3, 1, 7, 8])

---

##### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$


In [33]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2843, 2902, 8964, 2439, 1922],
       [ 184, 6717, 7082, 8022, 3412],
       [4158, 5013, 3519, 5333, 9895],
       [3156, 7077, 8391, 5608, 9293],
       [ 198, 3724, 1655, 9569, 6931],
       [1961, 4365, 2484, 7572, 6990],
       [4116, 6133, 2296, 5054, 9863],
       [3964, 7401, 4519, 5115, 4788]])

In [42]:
#Code here
print(arr1[:, ::2])

min_arr1 = np.min(arr1)
max_arr1 = np.max(arr1)

(arr1 - min_arr1)/(max_arr1 - min_arr1)

[[2843 8964 1922]
 [ 184 7082 3412]
 [4158 3519 9895]
 [3156 8391 9293]
 [ 198 1655 6931]
 [1961 2484 6990]
 [4116 2296 9863]
 [3964 4519 4788]]


array([[0.2738132 , 0.27988879, 0.90412934, 0.23221089, 0.1789723 ],
       [0.        , 0.67274225, 0.71032849, 0.80712594, 0.33240655],
       [0.40922665, 0.49727114, 0.34342498, 0.53022346, 1.        ],
       [0.30604469, 0.70981361, 0.84512409, 0.55854186, 0.93800844],
       [0.00144166, 0.36453506, 0.15147771, 0.96642982, 0.69477912],
       [0.18298836, 0.43054268, 0.23684482, 0.76078674, 0.7008547 ],
       [0.40490166, 0.61260426, 0.21748533, 0.50149315, 0.99670477],
       [0.3892493 , 0.74317784, 0.44640099, 0.50777469, 0.47410153]])

---

##### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [57]:
#Code here

arr = np.array([12,34,40,7,1,0])
n = 1

def nlargest(arr, n):
    if n <= len(arr):
        return np.sort(arr)[-n]
    else:
        print("Enter a smaller number")

nlargest(arr, n)

40

---

##### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [137]:
#code here
a = np.array([1,2,3])
print(np.append(np.repeat(a,3), np.tile(a,3)))

# OR
np.hstack([np.repeat(a,3), np.tile(a,3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])