### NumPy Tricks - Important Functions

---

In [1]:
import numpy as np

##### 1. np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [7]:
a = np.random.randint(1,100,15)
a

array([13, 87,  9, 80,  7, 59, 37, 50, 48, 37, 17, 10, 20, 39, 19])

In [8]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[38, 42, 67, 10],
       [ 7, 54, 66, 63],
       [75, 49, 41, 27],
       [38, 54, 16, 85],
       [23, 21, 86, 67],
       [33, 10, 19, 11]])

In [13]:
np.sort(a)

array([ 7,  9, 10, 13, 17, 19, 20, 37, 37, 39, 48, 50, 59, 80, 87])

In [4]:
np.sort(a)[::-1]

array([93, 88, 81, 77, 76, 76, 63, 54, 47, 45, 41, 24, 21, 19,  9])

In [16]:
np.sort(b, axis=1)

array([[10, 38, 42, 67],
       [ 7, 54, 63, 66],
       [27, 41, 49, 75],
       [16, 38, 54, 85],
       [21, 23, 67, 86],
       [10, 11, 19, 33]])

In [17]:
np.sort(b,axis=0)

array([[ 7, 10, 16, 10],
       [23, 21, 19, 11],
       [33, 42, 41, 27],
       [38, 49, 66, 63],
       [38, 54, 67, 67],
       [75, 54, 86, 85]])

---

##### 2. np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [18]:
a

array([13, 87,  9, 80,  7, 59, 37, 50, 48, 37, 17, 10, 20, 39, 19])

In [19]:
np.append(a,200)

array([ 13,  87,   9,  80,   7,  59,  37,  50,  48,  37,  17,  10,  20,
        39,  19, 200])

In [21]:
b

array([[38, 42, 67, 10],
       [ 7, 54, 66, 63],
       [75, 49, 41, 27],
       [38, 54, 16, 85],
       [23, 21, 86, 67],
       [33, 10, 19, 11]])

In [26]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[3.80000000e+01, 4.20000000e+01, 6.70000000e+01, 1.00000000e+01,
        1.39916327e-02],
       [7.00000000e+00, 5.40000000e+01, 6.60000000e+01, 6.30000000e+01,
        4.94549937e-01],
       [7.50000000e+01, 4.90000000e+01, 4.10000000e+01, 2.70000000e+01,
        7.87345480e-01],
       [3.80000000e+01, 5.40000000e+01, 1.60000000e+01, 8.50000000e+01,
        4.00344065e-01],
       [2.30000000e+01, 2.10000000e+01, 8.60000000e+01, 6.70000000e+01,
        6.19035678e-01],
       [3.30000000e+01, 1.00000000e+01, 1.90000000e+01, 1.10000000e+01,
        9.00090993e-01]])

In [27]:
np.append(b,np.random.random((1, b.shape[1])),axis=0)

array([[38.        , 42.        , 67.        , 10.        ],
       [ 7.        , 54.        , 66.        , 63.        ],
       [75.        , 49.        , 41.        , 27.        ],
       [38.        , 54.        , 16.        , 85.        ],
       [23.        , 21.        , 86.        , 67.        ],
       [33.        , 10.        , 19.        , 11.        ],
       [ 0.76908417,  0.57730547,  0.18407319,  0.48923823]])

---

##### 3. np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [28]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [29]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

---

##### 4. np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [31]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [32]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

---

##### 5. np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [35]:
a

array([13, 87,  9, 80,  7, 59, 37, 50, 48, 37, 17, 10, 20, 39, 19])

In [36]:
# code
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [37]:
np.expand_dims(a,axis=1).shape

(15, 1)

---

##### 6. np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [38]:
a

array([13, 87,  9, 80,  7, 59, 37, 50, 48, 37, 17, 10, 20, 39, 19])

In [39]:
# find all indices with value greater than 50
np.where(a>50)

(array([1, 3, 5], dtype=int64),)

In [40]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([13,  0,  9,  0,  7,  0, 37, 50, 48, 37, 17, 10, 20, 39, 19])

In [41]:
np.where(a%2 == 0,0,a)

array([13, 87,  9,  0,  7, 59, 37,  0,  0, 37, 17,  0,  0, 39, 19])

---

##### 7. np.argmax and np.argmin

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [42]:
# code
a

array([13, 87,  9, 80,  7, 59, 37, 50, 48, 37, 17, 10, 20, 39, 19])

In [46]:
print(np.argmax(a))
print(np.argmin(a))

1
4


In [47]:
b

array([[38, 42, 67, 10],
       [ 7, 54, 66, 63],
       [75, 49, 41, 27],
       [38, 54, 16, 85],
       [23, 21, 86, 67],
       [33, 10, 19, 11]])

In [48]:
np.argmax(b,axis=0)

array([2, 1, 4, 3], dtype=int64)

In [49]:
np.argmax(b,axis=1)

array([2, 2, 0, 3, 2, 0], dtype=int64)

In [ ]:
# np.argmin
np.argmin(a)

13

---

##### 8. np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [50]:
a

array([13, 87,  9, 80,  7, 59, 37, 50, 48, 37, 17, 10, 20, 39, 19])

In [51]:
np.cumsum(a)

array([ 13, 100, 109, 189, 196, 255, 292, 342, 390, 427, 444, 454, 474,
       513, 532])

In [54]:
b

array([[38, 42, 67, 10],
       [ 7, 54, 66, 63],
       [75, 49, 41, 27],
       [38, 54, 16, 85],
       [23, 21, 86, 67],
       [33, 10, 19, 11]])

In [56]:
np.cumsum(b,axis=0)

array([[ 38,  42,  67,  10],
       [ 45,  96, 133,  73],
       [120, 145, 174, 100],
       [158, 199, 190, 185],
       [181, 220, 276, 252],
       [214, 230, 295, 263]])

In [53]:
np.cumsum(b)

array([  38,   80,  147,  157,  164,  218,  284,  347,  422,  471,  512,
        539,  577,  631,  647,  732,  755,  776,  862,  929,  962,  972,
        991, 1002])

In [57]:
# np.cumprod
np.cumprod(a)

array([         13,        1131,       10179,      814320,     5700240,
         336314160,  -441277968,  -589061920,  1789798912,  1798050304,
         502084096,   725873664,  1632571392,  -754225152, -1445376000])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

---

##### 9. np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [58]:
a

array([13, 87,  9, 80,  7, 59, 37, 50, 48, 37, 17, 10, 20, 39, 19])

In [63]:
np.percentile(a,90)

71.6

In [60]:
np.median(a)

37.0

In [61]:
np.sort(a)

array([ 7,  9, 10, 13, 17, 19, 20, 37, 37, 39, 48, 50, 59, 80, 87])

---

##### 10. np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [64]:
# code
a

array([13, 87,  9, 80,  7, 59, 37, 50, 48, 37, 17, 10, 20, 39, 19])

In [65]:
import matplotlib.pyplot as plt

In [69]:
plt.bar(a,np.ones(15))

<BarContainer object of 15 artists>

In [70]:
np.histogram(a,bins=[0,30,60,100])

(array([7, 6, 2], dtype=int64), array([  0,  30,  60, 100]))

---

##### 11. np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [71]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([2,5,2.5,3,7])

np.corrcoef(salary,experience)

array([[1.        , 0.97161371],
       [0.97161371, 1.        ]])

---

##### 12. np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [72]:
# code
a

array([13, 87,  9, 80,  7, 59, 37, 50, 48, 37, 17, 10, 20, 39, 19])

In [75]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([80, 50, 10, 20])

---

##### 13. np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [76]:
# code
a

array([13, 87,  9, 80,  7, 59, 37, 50, 48, 37, 17, 10, 20, 39, 19])

In [77]:
np.flip(a)

array([19, 39, 20, 10, 17, 37, 48, 50, 37, 59,  7, 80,  9, 87, 13])

In [78]:
b

array([[38, 42, 67, 10],
       [ 7, 54, 66, 63],
       [75, 49, 41, 27],
       [38, 54, 16, 85],
       [23, 21, 86, 67],
       [33, 10, 19, 11]])

In [80]:
np.flip(b,axis=0)

array([[33, 10, 19, 11],
       [23, 21, 86, 67],
       [38, 54, 16, 85],
       [75, 49, 41, 27],
       [ 7, 54, 66, 63],
       [38, 42, 67, 10]])

---

##### 14. np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [81]:
# code
a

array([13, 87,  9, 80,  7, 59, 37, 50, 48, 37, 17, 10, 20, 39, 19])

In [83]:
np.put(a,[0,1],[110,530])

In [85]:
a

array([110, 530,   9,  80,   7,  59,  37,  50,  48,  37,  17,  10,  20,
        39,  19])

---

##### 15. np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [86]:
# code
a

array([110, 530,   9,  80,   7,  59,  37,  50,  48,  37,  17,  10,  20,
        39,  19])

In [87]:
np.delete(a,[0,2,4])

array([530,  80,  59,  37,  50,  48,  37,  17,  10,  20,  39,  19])

In [88]:
a

array([110, 530,   9,  80,   7,  59,  37,  50,  48,  37,  17,  10,  20,
        39,  19])

---

##### 16.  Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [89]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [91]:
np.intersect1d(m,n)

array([3, 4, 5])

In [93]:
np.setdiff1d(n,m)

array([6, 7])

In [94]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

---

##### 17. np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [95]:
# code
a

array([110, 530,   9,  80,   7,  59,  37,  50,  48,  37,  17,  10,  20,
        39,  19])

In [96]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 75, 25, 59, 37, 50, 48, 37, 25, 25, 25, 39, 25])

---

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals

In [ ]:
np.