### Numpy Tricks - TASK

---

In [1]:
import numpy as np

##### `Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [26]:
# code here
arr = np.array(
    [[92, 90, 74],
    [ 6, 63, 93],
    [15, 93, 96],
    [70, 60, 48]])

# Ques 1
print(np.sort(arr))
print()

# Ques 2
arr[:,1:2] = np.sort(arr[:,1:2])
print(arr)
print()

# Ques 3
print(np.sort(arr, axis=0))
print()

# Ques 4
print(np.sort(arr.flatten()).reshape(arr.shape))

[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

[[92 90 74]
 [ 6 63 93]
 [15 93 96]
 [70 60 48]]

[[ 6 60 48]
 [15 63 74]
 [70 90 93]
 [92 93 96]]

[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]


---

##### `Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [86]:
# code here
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

extra_subject = np.array([41, 87, 72, 36, 92])

#Two extra students record-
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

# Ques 1
marks = np.append(marks, extra_subject.reshape(-1,1), axis=1)
print(marks)
print()

# Ques 2
marks = np.append(marks, rec1.reshape(-1,1), axis=1)
marks = np.append(marks, rec2.reshape(-1,1), axis=1)
print(marks)
print()

# Ques 3
marks = np.append(marks, np.sum(marks, axis=1).reshape(-1,1), axis=1)
print(marks)
print()

# OR

# code here
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1, 1)
marks = np.concatenate([marks, extra_subject], axis = 1)
print(marks)

#2
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1, -1)
rec2 = np.array( [92, 71, 52, 61, 53]).reshape(1, -1)
marks = np.concatenate([marks, rec1, rec2], axis = 0)
print(marks)

#3
sum_of_stud = marks.sum(axis = 1, keepdims=True)
marks = np.concatenate([marks, sum_of_stud], axis = 1)
print(marks)

#4
print(np.array(sorted(marks, key = lambda x: x[-1], reverse=True)))

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]

[[13 10  9 33 41 77 92]
 [63 46 90 42 87 83 71]
 [39 76 13 29 72 98 52]
 [82  9 29 78 36 95 61]
 [67 61 59 36 92 89 53]]

[[ 13  10   9  33  41  77  92 275]
 [ 63  46  90  42  87  83  71 482]
 [ 39  76  13  29  72  98  52 379]
 [ 82   9  29  78  36  95  61 390]
 [ 67  61  59  36  92  89  53 457]]

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]
[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]
[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]
[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]
 [ 63  46  90  42  87 328]
 [ 67  61  59  36  92 315]
 [ 82   9  29  78  36 234]
 [ 39  76  13  29  72 229]
 [ 13  10   9  33  41 106]]


---

##### `Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [69]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

# Row wise
print(np.unique(arr, axis=0))
print()

# Column wise
print(np.unique(arr, axis=1))

[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


---

##### `Q-4:` Flip given 2-D array along both axes at the same time.

In [87]:
# code here
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

flipped_array = np.rot90(arr, 2)

print(flipped_array)

# OR

np.flip(arr, axis = [0, 1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

---

##### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

---

In [88]:
# code here
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]] )
X = 6

np.where(np.any(arr > X, axis = 1))

(array([1, 3], dtype=int64),)

---

##### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [71]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [89]:
# code here
np.concatenate([arr1, arr2, arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

---

##### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [93]:
# code here
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
arr = arr[(arr != arr.min()) & (arr != arr.max())]

# OR
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
max_element = arr.argmax()
min_element = arr.argmin()
print(arr.max(), arr.min())
arr = np.delete(arr, max_element, axis = 1)
arr = np.delete(arr, min_element, axis = 1)
print(arr.max(), arr.min())

985 100
981 102


---

##### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [94]:
# code here
arr = np.random.randint(0, 2000, 500)
np.cumsum(np.sort(np.clip(arr, 100, 200)))

array([  100,   200,   300,   400,   500,   600,   700,   800,   900,
        1000,  1100,  1200,  1300,  1400,  1500,  1600,  1700,  1800,
        1900,  2000,  2112,  2229,  2353,  2479,  2607,  2735,  2864,
        3000,  3143,  3288,  3434,  3584,  3742,  3901,  4064,  4240,
        4419,  4603,  4788,  4973,  5159,  5359,  5559,  5759,  5959,
        6159,  6359,  6559,  6759,  6959,  7159,  7359,  7559,  7759,
        7959,  8159,  8359,  8559,  8759,  8959,  9159,  9359,  9559,
        9759,  9959, 10159, 10359, 10559, 10759, 10959, 11159, 11359,
       11559, 11759, 11959, 12159, 12359, 12559, 12759, 12959, 13159,
       13359, 13559, 13759, 13959, 14159, 14359, 14559, 14759, 14959,
       15159, 15359, 15559, 15759, 15959, 16159, 16359, 16559, 16759,
       16959, 17159, 17359, 17559, 17759, 17959, 18159, 18359, 18559,
       18759, 18959, 19159, 19359, 19559, 19759, 19959, 20159, 20359,
       20559, 20759, 20959, 21159, 21359, 21559, 21759, 21959, 22159,
       22359, 22559,

---

##### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [95]:
# code here
arr = np.random.random(100)
arr = np.around(arr, decimals = 3)

print("0th percentile == minimum value of the array: ", (np.percentile(arr, 0) == arr.min()))
print("100th percentile == maximum value of the array: ", (np.percentile(arr, 100) == arr.max()))
print("difference betwen 51th percenile and 50th percentile values: ", (np.percentile(arr, 51) - np.percentile(arr, 50)))

0th percentile == minimum value of the array:  True
100th percentile == maximum value of the array:  True
difference betwen 51th percenile and 50th percentile values:  0.004489999999999994
